{
 "title": "Bitcoin",
 "time": { "from": "now-7d", "to": "now" },
 "panels": [
  {
   "title": "120d成長倍率",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "t1 = from(bucket: \"quote\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"daily\" and\r\n    r.valmean == \"open\" and\r\n    r.name == \"bitcoin\"\r\n  )\r\n\r\nt2 = from(bucket: \"quote\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"daily\" and\r\n    r.valmean == \"open\" and\r\n    r.name == \"bitcoin\"\r\n  )\r\n  |> timeShift(duration: 120d)\r\n\r\n\r\njoin(tables: {t1: t1, t2: t2}, on: [\"_time\"])\r\n    |> map(fn: (r) => ({ r with _value: (r._value_t1 - r._value_t2)/r._value_t2     }))\r\n    |>map(fn: (r) => ({ r with alias: \"120d 投資比\" }))      \r\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "t1 = from(bucket: \"quote\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"daily\" and\r\n    r.valmean == \"open\" and\r\n    r.name == \"bitcoin\"\r\n  )\r\n  |> difference()\r\nt2 = from(bucket: \"quote\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"daily\" and\r\n    r.valmean == \"open\" and\r\n    r.name == \"bitcoin\"\r\n  )\r\n\r\njoin(tables: {t1: t1, t2: t2}, on: [\"_time\"])\r\n    |> map(fn: (r) => ({ r with _value: r._value_t1 /r._value_t2 * 100.00   }))\r\n    |>map(fn: (r) => ({ r with alias: \"90d加速比\" }))     \r\n    |>movingAverage(n: 90)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "t1 = from(bucket: \"quote\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"daily\" and\r\n    r.valmean == \"high\" and\r\n    r.name == \"bitcoin\"\r\n  )\r\n  t1\r\n\r\nt2 = from(bucket: \"quote\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"daily\" and\r\n    r.valmean == \"high\" and\r\n    r.name == \"bitcoin\"\r\n  )  \r\n  |>movingAverage(n: 365)\r\n\r\n  \r\njoin(tables: {t1: t1, t2: t2}, on: [\"_time\"])\r\n    |> map(fn: (r) => ({ r with _value: (r._value_t1 - r._value_t2) / r._value_t2   })) \r\n    |>map(fn: (r) => ({ r with alias: \"年增幅比\" }))     \r\n    ",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "t1 = from(bucket: \"quote\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"daily\" and\r\n    r.valmean == \"open\" and\r\n    r.name == \"bitcoin\"\r\n  )\r\n  |> difference()\r\n  |>movingAverage(n: 120)\r\n  |> difference()\r\n  |>movingAverage(n: 120)\r\n\r\n\r\n\r\n  t2 = from(bucket: \"quote\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"daily\" and\r\n    r.valmean == \"open\" and\r\n    r.name == \"bitcoin\"\r\n  )\r\n |>movingAverage(n: 365)\r\n\r\n\r\n\r\n\r\n join(tables: {t1: t1, t2: t2}, on: [\"_time\"])\r\n    |> map(fn: (r) => ({ r with _value: (r._value_t1 /r._value_t2)* 10000.00 ,  alias: \"加速度\"   }))",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "t1 = from(bucket: \"quote\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"daily\" and\r\n    r.valmean == \"open\" and\r\n    r.name == \"bitcoin\"\r\n  )\r\n  |> difference()\r\nt2 = from(bucket: \"quote\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"daily\" and\r\n    r.valmean == \"open\" and\r\n    r.name == \"bitcoin\"\r\n  )\r\n\r\njoin(tables: {t1: t1, t2: t2}, on: [\"_time\"])\r\n    |> map(fn: (r) => ({ r with _value: r._value_t1 /r._value_t2 * 100.00   }))\r\n    |>movingAverage(n: 120)\r\n    |> difference()\r\n    |> map(fn: (r) => ({ r with _value: r._value * 100.00 ,  alias: \"切線加速度\"  }))\r\n    |>movingAverage(n: 30)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "各均線比較",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "t1 = from(bucket: \"quote\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"daily\" and\r\n    r.valmean == \"high\" and\r\n    r.name == \"bitcoin\"\r\n  )\r\n  |>map(fn: (r) => ({ r with alias: \"Current\" }))\r\n\r\n  t1",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "t2 = from(bucket: \"quote\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"daily\" and\r\n    r.valmean == \"high\" and\r\n    r.name == \"bitcoin\"\r\n  )\r\n  |>movingAverage(n: 60)\r\n  |>map(fn: (r) => ({ r with alias: \"60Day均線\" }))\r\nt2",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "t1 = from(bucket: \"quote\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"daily\" and\r\n    r.valmean == \"high\" and\r\n    r.name == \"bitcoin\"\r\n  )\r\n  |>movingAverage(n: 120)\r\n  |>map(fn: (r) => ({ r with alias: \"120Day均線\" }))\r\n\r\nt1",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "t1 = from(bucket: \"quote\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"daily\" and\r\n    r.valmean == \"high\" and\r\n    r.name == \"bitcoin\"\r\n  )\r\n  |>movingAverage(n: 30)\r\n  |>map(fn: (r) => ({ r with alias: \"30Day均線\" }))  \r\n\r\nt1",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "t1 = from(bucket: \"quote\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"daily\" and\r\n    r.valmean == \"high\" and\r\n    r.name == \"bitcoin\"\r\n  )\r\n  |>movingAverage(n: 30)\r\n\r\nt2 = from(bucket: \"quote\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"daily\" and\r\n    r.valmean == \"high\" and\r\n    r.name == \"bitcoin\"\r\n  )\r\n  |>movingAverage(n: 60)\r\n\r\n\r\nj1=join(tables: {t1: t1, t2: t2}, on: [\"_time\"])\r\n    |> map(fn: (r) => ({ \r\n        r with \r\n        _value: (r._value_t1 -r._value_t2)+r._value_t1 ,\r\n        alias: \"60+30Day差\"\r\n        }))\r\nj1\r\n\r\n\r\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "30D 顆數乖離",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "import \"date\"\r\nt1= from(bucket: \"quote\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"daily\" and\r\n    r.valmean == \"volume\"  and\r\n    r.name == \"bitcoin\"\r\n  )\r\n  |> map(fn: (r) => ({ r with _time: date.truncate(t: r._time, unit: 1d)    }))\r\n\r\n\r\nt2= from(bucket: \"quote\")\r\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"daily\" and\r\n    r.valmean == \"open\"  and\r\n    r.name == \"bitcoin\"\r\n  )\r\n  |> map(fn: (r) => ({ r with _time: date.truncate(t: r._time, unit: 1d)    }))\r\n\r\nt3 = join(tables: {t1: t1, t2: t2}, on: [\"_time\"])\r\n    |> map(fn: (r) => ({ r with _value: r._value_t1 /r._value_t2     }))\r\n\r\nt4 = t3\r\n    |>movingAverage(n: 30)\r\n\r\nt5 = join(tables: {t1: t3, t2: t4}, on: [\"_time\"])\r\n    |> map(fn: (r) => ({ r with _value: (r._value_t1-r._value_t2) /r._value_t2 ,alias: \"顆數乖離率\"    }))\r\n\r\nt5\r\n\r\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}